[参考资料](https://segmentfault.com/a/1190000039264963)

- widow.onerror
  同步错误可以捕获到，但是，请注意 window.error 无法捕获静态资源异常和 JS 代码错误。

```js
/**
 * @param {String}  message    错误信息
 * @param {String}  source     出错文件
 * @param {Number}  lineno     行号
 * @param {Number}  colno      列号
 * @param {Object}  error      Error对象（对象）
 */
window.onerror = function (message, source, lineno, colno, error) {
  console.log("捕获到异常：", { message, source, lineno, colno, error });
};
```

- addEventListener("error")
  能检测到静态资源的错误

```js
window.addEventListener(
  "error",
  (error) => {
    console.log("捕获到异常：", error);
  },
  true
);
```

由于网络请求异常不会事件冒泡，因此必须在捕获阶段将其捕捉到才行，但是这种方式虽然可以捕捉到网络请求的异常，但是无法判断 HTTP 的状态是 404 还是其他比如 500 等等，所以还需要配合服务端日志才进行排查分析才可以。

- unhandledrejection
  Promise 中的异常不能被 try-catch 和 window.onerror 捕获，这时候我们就需要监听

```js
window.addEventListener("unhandledrejection", function (e) {
  e.preventDefault();
  console.log("捕获到 promise 错误了");
  console.log("错误的原因是", e.reason);
  console.log("Promise 对象是", e.promise);
  return true;
});

Promise.reject("promise error");
new Promise((resolve, reject) => {
  reject("promise error");
});
new Promise((resolve) => {
  resolve();
}).then(() => {
  throw "promise error";
});
```

- componentDidCatch
  用于 react 组件的异常

- errorHandler
  用于 vue 组件的异常

- axios.interceptors
  用户请求异常

## 异常分类

- 可疑区域增加 try-catch
- 全局监控 JS 异常 window.onerror
- 全局监控静态资源异常 window.addEventListener
- 捕获没有 catch 的 Promise 异常用 unhandledrejection
- Vue errorHandler 和 React componentDidCatch
- Axios 请求统一异常处理用拦截器 interceptors
- 使用日志监控服务收集用户错误信息

## 异常上报

ARMS、fundebug、BadJS、Sentry

[前端错误监控方案 sentry 方案](https://juejin.cn/post/6875955097864994823)
[Sentry Web 前端监控-官方教程](https://juejin.cn/post/7007607369962094599)
